#!/usr/bin/env python3
"""
Purria Starter - Environment Initializer
Creates template .env files for a new Purria project.
"""
import os
import secrets
import sys
from pathlib import Path

# ANSI colors
GREEN = "\033[92m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
RESET = "\033[0m"
BOLD = "\033[1m"


def generate_secret(length=32):
    """Generate a secure random secret."""
    return secrets.token_urlsafe(length)


SERVER_ENV_TEMPLATE = """# Farming in Purria - Server Environment
# Generated by purria-starter

# Authentication
BETTER_AUTH_SECRET={auth_secret}
BETTER_AUTH_URL=http://localhost:5172

# CORS - must match web app port
CORS_ORIGIN=http://localhost:5173

# Database
DATABASE_URL=file:../../local.db
"""

WEB_ENV_TEMPLATE = """# Farming in Purria - Web Environment
# Generated by purria-starter

VITE_SERVER_URL=http://localhost:5172
"""

SHELL_EXPORTS = """
# Farming in Purria - API Keys
# Add these to your shell profile (~/.bashrc, ~/.zshrc, or PowerShell $PROFILE)

export GEMINI_API_KEY="your-gemini-api-key-here"
export RECRAFT_API_KEY="your-recraft-api-key-here"

# Get API keys from:
# - Gemini: https://aistudio.google.com/apikey
# - Recraft: https://recraft.ai
"""


def create_env_file(path: Path, content: str, description: str):
    """Create an env file if it doesn't exist."""
    if path.exists():
        print(f"  {YELLOW}!{RESET} {description} already exists: {path}")
        return False

    # Create parent directories
    path.parent.mkdir(parents=True, exist_ok=True)

    path.write_text(content)
    print(f"  {GREEN}✓{RESET} Created {description}: {path}")
    return True


def main():
    print(f"\n{BOLD}Purria Starter - Environment Initializer{RESET}")
    print("=" * 45)

    # Find project root
    cwd = Path.cwd()

    # Check if we're in a Purria project
    if not (cwd / "turbo.json").exists() and not (cwd / "CLAUDE.md").exists():
        # Try parent directory
        if (cwd.parent / "turbo.json").exists():
            cwd = cwd.parent
        else:
            print(f"\n{YELLOW}Warning: Not in a Purria project directory{RESET}")
            print(f"Current: {cwd}")
            response = input("Continue anyway? (y/n): ")
            if response.lower() != 'y':
                return 1

    print(f"\nProject root: {cwd}\n")

    # Generate auth secret
    auth_secret = generate_secret(32)

    # Create server .env
    print(f"{BLUE}Creating environment files...{RESET}\n")

    server_env_path = cwd / "apps" / "server" / ".env"
    server_content = SERVER_ENV_TEMPLATE.format(auth_secret=auth_secret)
    create_env_file(server_env_path, server_content, "Server .env")

    # Create web .env
    web_env_path = cwd / "apps" / "web" / ".env"
    create_env_file(web_env_path, WEB_ENV_TEMPLATE, "Web .env")

    # Show shell exports
    print(f"\n{BLUE}API Key Configuration{RESET}")
    print("-" * 40)
    print(SHELL_EXPORTS)

    # Check current API keys
    print(f"\n{BLUE}Current API Key Status:{RESET}")
    gemini_key = os.environ.get("GEMINI_API_KEY", "")
    recraft_key = os.environ.get("RECRAFT_API_KEY", "")

    if gemini_key:
        print(f"  {GREEN}✓{RESET} GEMINI_API_KEY: Set ({len(gemini_key)} chars)")
    else:
        print(f"  {YELLOW}!{RESET} GEMINI_API_KEY: Not set")

    if recraft_key:
        print(f"  {GREEN}✓{RESET} RECRAFT_API_KEY: Set ({len(recraft_key)} chars)")
    else:
        print(f"  {YELLOW}!{RESET} RECRAFT_API_KEY: Not set")

    print(f"\n{GREEN}Environment initialization complete!{RESET}")
    print("\nNext steps:")
    print("  1. Set API keys in your shell profile")
    print("  2. Run: bun install")
    print("  3. Run: bun db:push")
    print("  4. Run: bun dev")

    return 0


if __name__ == "__main__":
    sys.exit(main())
